# fly.toml app configuration file generated for kttt on 2025-07-09T21:58:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kttt'
primary_region = 'sjc'

[build]
  [build.args]
    VITE_CLOUDFLARE_ANALYTICS_TOKEN = "12a9b6af36c843348eba671ae8683b65"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  PORT = "3000"
  NODE_ENV = "production"
  REDIS_TTL_SECONDS = "14400"
  REDIS_CONNECTION_TIMEOUT_MS = "5000"
  VITE_CLOUDFLARE_ANALYTICS_TOKEN = "12a9b6af36c843348eba671ae8683b65"
